# Generated by Django 2.2.12 on 2020-06-16 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColaborador', models.CharField(max_length=40)),
                ('link', models.URLField(max_length=500, null=True)),
                ('logo', models.ImageField(null=True, upload_to='ColaboradorL/')),
                ('foto', models.ImageField(null=True, upload_to='ColaboradorF/')),
                ('mision', models.CharField(blank=True, max_length=400, null=True)),
                ('fecha', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('nombreProyecto', models.CharField(max_length=40, null=True)),
                ('descripcion', models.CharField(max_length=300, null=True)),
                ('imagen', models.ImageField(upload_to='proyecto/')),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('proyecto_del_año', models.BooleanField(default=True, verbose_name='proyecto_del_año')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRecurso', models.CharField(max_length=40)),
                ('archivo', models.FileField(null=True, upload_to='transferencias/')),
                ('link', models.URLField(blank=True, null=True)),
                ('imagen', models.ImageField(null=True, upload_to='recursos/')),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.Proyecto')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('link', models.URLField(max_length=500)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('imagen', models.ImageField(default='pic_folder/None/partner-3.png', upload_to='noticia/')),
                ('body', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-fecha'],
            },
        ),
    ]
